// SPDX-License-Identifier: Apache-2.0
// This code has been partially generated by an AI.

package plugin

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// Publisher uploads release artifacts to a generic HTTP endpoint.
type Publisher struct {
	name string
}

type Provider interface {
	Name() string
	HealthCheck(context.Context) error
}

func NewPublisher(name string) *Publisher {
	if name == "" {
		name = "publisher-generic-http"
	}

	return &Publisher{name: name}
}

func (p *Publisher) Name() string {
	return p.name
}

func (p *Publisher) HealthCheck(context.Context) error {
	return nil
}

func ParseArtifacts(getenv func(string) string) ([]string, error) {
	if raw := strings.TrimSpace(getenv("SEMREL_PLUGIN_ARTIFACTS")); raw != "" {
		parts := strings.Split(raw, ",")
		artifacts := make([]string, 0, len(parts))
		for _, item := range parts {
			trimmed := strings.TrimSpace(item)
			if trimmed != "" {
				artifacts = append(artifacts, trimmed)
			}
		}
		if len(artifacts) > 0 {
			return artifacts, nil
		}
	}

	if raw := strings.TrimSpace(getenv("SEMREL_PLUGIN_ARTIFACTS_JSON")); raw != "" {
		var artifacts []string
		if err := json.Unmarshal([]byte(raw), &artifacts); err != nil {
			return nil, fmt.Errorf("parse SEMREL_PLUGIN_ARTIFACTS_JSON: %w", err)
		}
		if len(artifacts) > 0 {
			return artifacts, nil
		}
	}

	if single := strings.TrimSpace(getenv("SEMREL_PLUGIN_ARTIFACT")); single != "" {
		return []string{single}, nil
	}

	return nil, fmt.Errorf("no artifacts configured (SEMREL_PLUGIN_ARTIFACTS, SEMREL_PLUGIN_ARTIFACTS_JSON, or SEMREL_PLUGIN_ARTIFACT)")
}

func ResolveURL(urlTemplate, version, artifact string) string {
	resolved := strings.ReplaceAll(urlTemplate, "{version}", version)
	resolved = strings.ReplaceAll(resolved, "{artifact}", filepath.Base(artifact))
	if !strings.Contains(urlTemplate, "{artifact}") {
		if strings.HasSuffix(resolved, "/") {
			resolved += filepath.Base(artifact)
		} else {
			resolved += "/" + filepath.Base(artifact)
		}
	}
	return resolved
}

func ParseHeaders(getenv func(string) string) (map[string]string, error) {
	headers := map[string]string{}
	if raw := strings.TrimSpace(getenv("SEMREL_PLUGIN_HEADERS_JSON")); raw != "" {
		if err := json.Unmarshal([]byte(raw), &headers); err != nil {
			return nil, fmt.Errorf("parse SEMREL_PLUGIN_HEADERS_JSON: %w", err)
		}
	}
	return headers, nil
}

func UploadArtifact(client *http.Client, method, url string, headers map[string]string, token, artifact string) error {
	return uploadArtifact(client, method, url, headers, token, artifact, time.Now, time.Sleep)
}

func uploadArtifact(
	client *http.Client,
	method, url string,
	headers map[string]string,
	token, artifact string,
	now func() time.Time,
	sleep func(time.Duration),
) error {
	body, err := os.ReadFile(artifact)
	if err != nil {
		return fmt.Errorf("read artifact %s: %w", artifact, err)
	}

	for attempt := 0; attempt < uploadAttempts; attempt++ {
		req, err := http.NewRequest(method, url, bytes.NewReader(body))
		if err != nil {
			return fmt.Errorf("build request: %w", err)
		}

		req.Header.Set("Content-Type", "application/octet-stream")
		if token != "" {
			req.Header.Set("Authorization", "Bearer "+token)
		}
		for key, value := range headers {
			req.Header.Set(key, value)
		}

		resp, err := client.Do(req)
		if err != nil {
			return fmt.Errorf("http upload: %w", err)
		}

		if resp.StatusCode >= 200 && resp.StatusCode < 300 {
			_ = resp.Body.Close()
			return nil
		}

		snippet, _ := io.ReadAll(io.LimitReader(resp.Body, 2048))
		status := resp.StatusCode
		retryAfter := retryAfterDelay(resp.Header.Get("Retry-After"), now())
		_ = resp.Body.Close()
		if status == http.StatusTooManyRequests && attempt+1 < uploadAttempts {
			sleep(retryAfter)
			continue
		}
		return fmt.Errorf("upload failed with status %d: %s", status, strings.TrimSpace(string(snippet)))
	}

	return fmt.Errorf("upload failed after %d attempts", uploadAttempts)
}

func DefaultHTTPClient() *http.Client {
	return &http.Client{Timeout: 60 * time.Second}
}

const uploadAttempts = 3

// maxRetryAfterDelay caps each server-requested pause; three attempts wait at most one minute total.
const maxRetryAfterDelay = 30 * time.Second

func retryAfterDelay(value string, now time.Time) time.Duration {
	value = strings.TrimSpace(value)
	seconds, err := strconv.ParseUint(value, 10, 64)
	if err == nil {
		if seconds >= uint64(maxRetryAfterDelay/time.Second) {
			return maxRetryAfterDelay
		}
		return time.Duration(seconds) * time.Second
	}

	retryAt, err := http.ParseTime(value)
	if err == nil {
		delay := retryAt.Sub(now)
		if delay < 0 {
			return 0
		}
		if delay > maxRetryAfterDelay {
			return maxRetryAfterDelay
		}
		return delay
	}

	return 100 * time.Millisecond
}
